name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: choice
        options:
          - hello
          - hola
          - nihao
jobs:
  run:  # ジョブID
    runs-on: ubuntu-latest
    steps:  # ステップの定義
      - run: echo "${{ inputs.greeting }}"
