name: Manual
on:
  workflow_dispatch:
    in:
      greeting:
        type: string
        default: hello
        required: true
        description: A cheerful word
jobs:
  run:  # ジョブID
    runs-on: ubuntu-latest
    steps:  # ステップの定義
      - run: echo "${{ in.greeting }}"
